
development:
  adapter: postgresql
  username: benson
  password: ******
  url: postgresql://localhost/sample_app_development?pool=5

test:
  adapter: postgresql
  username: benson
  password: ******
  url: postgresql://localhost/sample_app_test?pool=5

production:
  adapter: postgresql
  username: benson
  password: ******
  url: postgresql://localhost/sample_app_production?pool=5
